In [1]:
import pandas as pd

In [2]:
hot = pd.read_csv("billboardHot100_1999-2019.csv")
spot = pd.read_csv("songAttributes_1999-2019.csv")

In [3]:
hot.head(25)

,Unnamed: 0,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Date,Genre,Writing.Credits,Lyrics,Features
0,1,"Lil Nas,",Old Town Road,1,1.0,7.0,2019-07-06,"April 5, 2019","Country,Atlanta,Alternative Country,Hip-Hop,Tr...","Jozzy, Atticus ross, Trent reznor, Billy ray c...","Old Town Road Remix \nOh, oh-oh\nOh\nYeah, I'm...",Billy Ray Cyrus
1,2,"Shawn Mendes, Camila Cabello",Senorita,2,NaN,NaN,2019-07-06,"June 21, 2019",Pop,"Cashmere cat, Jack patterson, Charli xcx, Benn...",Senorita \nI love it when you call me senorita...,NaN
2,3,Billie Eilish,Bad Guy,3,2.0,13.0,2019-07-06,"March 29, 2019","Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ...","Billie eilish, Finneas","bad guy \nWhite shirt now red, my bloody nose\...",NaN
3,4,Khalid,Talk,4,3.0,20.0,2019-07-06,"February 7, 2019","Synth-Pop,Pop","Howard lawrence, Guy lawrence, Khalid",Talk \nCan we just talk? Can we just talk?\nTa...,NaN
4,5,"Ed Sheeran, Justin Bieber",I Don't Care,5,2.0,7.0,2019-07-06,"May 10, 2019","Canada,UK,Dance,Dance-Pop,Pop","Ed sheeran, Justin bieber, Shellback, Max mart...",I Don't Care \nI'm at a party I don't wanna be...,NaN
5,6,Jonas Brothers,Sucker,6,1.0,17.0,2019-07-06,"March 1, 2019","Alternative Pop,Boy Band,Teen Pop,Pop-Rock,Pop","Ryan tedder, Louis bell, Frank dukes, Nick jon...",Sucker \nWe go together\nBetter than birds of ...,NaN
6,7,DaBaby,Suge,7,7.0,13.0,2019-07-06,"March 1, 2019","Trap,East Coast,Rap","Jetsonmade, Pooh beatz, Dababy","Suge \nPooh, you a fool for this one\nHa\nOh L...",NaN
7,8,Drake,Money In The Grave,8,7.0,2.0,2019-07-06,"June 15, 2019","Hip-Hop,Rap,Basketball,NBA,Canada","Asoteric, Ljay currie, Cydney christine, Rick ...","Money in the Grave \nYeah, okay\nLil CC on the...",Rick Ross
8,9,Chris Brown,No Guidance,9,9.0,3.0,2019-07-06,"June 8, 2019","Alternative R&;B,Hip-Hop,Rap,Pop,DMV,Canada,R&;B","Velous, J louis, Vinylz, Michee patrick lebrun...","No Guidance \nBefore I die I'm tryna fuck you,...",Drake
9,10,Post Malone,Wow.,10,2.0,27.0,2019-07-06,"December 24, 2018","Memes,Hip-Hop,Trap,Rap","Frank dukes, Billy walsh, Louis bell, Post malone","Wow \nSaid she tired of little money, need a b...",NaN
10,11,Lizzo,Truth Hurts,11,11.0,8.0,2019-07-06,"September 19, 2017","Pop,Rap","Ricky reed, Jesse saint john, Steven cheung, L...",Truth Hurts \nWhy're men great til they gotta ...,NaN
11,12,"Post Malone, Swae Lee",Sunflower,12,1.0,36.0,2019-07-06,"October 18, 2018","Rap,Disney,Hip-Hop,Marvel,Soundtrack,R&;B,Pop","Carl rosen, Louis bell, Billy walsh, Carter la...","Sunflower \nAyy, ayy, ayy, ayy Ooh\nOoh, ooh, ...",NaN
12,13,Taylor Swift,You Need To Calm Down,13,2.0,2.0,2019-07-06,"June 14, 2019","Synth-Pop,LGBTQ+,Pop","Joel little, Taylor swift",You Need To Calm Down \nYou are somebody that ...,NaN
13,14,Shawn Mendes,If I Can't Have You,14,2.0,8.0,2019-07-06,"May 3, 2019","Canada,Teen Pop,Pop","Dmitry fedorov, Teddy geiger, Shawn mendes, Sc...",If I Can't Have You \nI can't write one song t...,NaN
14,15,"Sam Smith, Normani",Dancing With A Stranger,15,7.0,24.0,2019-07-06,"January 11, 2019","UK,Pop","Tor erik hermansen, Mikkel storleer eriksen, J...","Dancing with a Stranger \nHmm, mhm\nI don't wa...",NaN
15,16,Lil Nas X,Panini,16,NaN,NaN,2019-07-06,"June 20, 2019","Memes,Atlanta,Hip-Hop,Trap,Rap","Dot da genius, Kurt cobain, David biral, Denze...","Panini \nDaytrip took it to 10 Hey\nAyy, Panin...",NaN
16,17,Halsey,Without Me,17,1.0,38.0,2019-07-06,"October 4, 2018","Synth-Pop,R&;B,Alternative Pop,Ballad,Pop,Alte...","Justin timberlake, Timbaland, Halsey, Delacey,...",Without Me \nFound you when your heart was bro...,NaN
17,18,Blake Shelton,God's Country,18,18.0,13.0,2019-07-06,"March 29, 2019",Country,"Jordan schmidt, Hardy, Devin dawson",God's Country \nRight outside of this one chur...,NaN
18,19,Polo G,Pop Out,19,11.0,14.0,2019-07-06,"January 13, 2019","Trap,Rap","Lil tjay, Polo g","Pop Out \nJD On Tha Track\nIceberg want a bag,...",Lil Tjay
19,20,Nicki Minaj,MEGATRON,20,NaN,NaN,2019-07-06,"June 21, 2019","East Coast,Hip-Hop,Rap","Haldane brown, Andrew pop wansel, Brittany con...",MEGATRON \nBrra-ta-ta-ta\nBrra-ta-ta-ta\nThey ...,NaN
20,21,Ava Max,Sweet But Psycho,21,10.0,28.0,2019-07-06,"August 17, 2018","Dance-Pop,Dance,Electronic Pop,Electro,R&;B,El...","Ava max, Tix, Cirkut, Madison love, Cook classics","Sweet But Psycho \nOh, she's sweet but a psych...",NaN
21,22,"Lil Nas X, Cardi B",Rodeo,22,NaN,NaN,2019-07-06,"June 21, 2019","Country,Atlanta,East Coast,Trap,Country Rap,Hi...","Denzel baptiste, Russ chell, Roy lenzo, Cardi ...","Rodeo \nDaytrip took it to 10 Hey\nOh, here we...",NaN
22,23,Ariana Grande,7 Rings,23,1.0,23.0,2019-07-06,"January 18, 2019","Memes,Trap,R&;B,Pop","Ariana grande, Richard rodgers, Tbhits, Njomza...","7 rings \nYeah, breakfast at Tiffany's and bot...",NaN
23,24,Panic! At The Disco,"Hey Look Ma, I Made It",24,24.0,11.0,2019-07-06,"June 22, 2018","Pop-Rock,Jazz Fusion,Alternative,Alternative P...","Jake sinclair, Michael angelakos, Dillon franc...","Hey Look Ma, I Made It \nAll my life, been hus...",NaN
24,25,"Marshmello, Bastille",Happier,25,2.0,45.0,2019-07-06,"August 17, 2018","Adult Alternative,Producer,Alternative Dance,A...","Steve mac, Marshmello, Dan smith","Happier \nLately, I've been, I've been thinkin...",NaN

In [4]:
spot.columns

Index(['Unnamed: 0', 'Acousticness', 'Album', 'Artist', 'Danceability',
       'Duration', 'Energy', 'Explicit', 'Instrumentalness', 'Liveness',
       'Loudness', 'Mode', 'Name', 'Popularity', 'Speechiness', 'Tempo',
       'TimeSignature', 'Valence'],
      dtype='object')

In [5]:
new_df = hot.merge(spot, left_on=["Artists", "Name"], right_on=["Artist", "Name"])

In [6]:
new_df.columns

Index(['Unnamed: 0_x', 'Artists', 'Name', 'Weekly.rank', 'Peak.position',
       'Weeks.on.chart', 'Week', 'Date', 'Genre', 'Writing.Credits', 'Lyrics',
       'Features', 'Unnamed: 0_y', 'Acousticness', 'Album', 'Artist',
       'Danceability', 'Duration', 'Energy', 'Explicit', 'Instrumentalness',
       'Liveness', 'Loudness', 'Mode', 'Popularity', 'Speechiness', 'Tempo',
       'TimeSignature', 'Valence'],
      dtype='object')

In [7]:
new_df.drop(["Unnamed: 0_x", "Unnamed: 0_y"], axis=1, inplace=True)

In [8]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 67161 entries, 0 to 67160
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artists           67161 non-null  object
 1   Name              67161 non-null  object
 2   Weekly.rank       67161 non-null  int64
 3   Peak.position     62933 non-null  float64
 4   Weeks.on.chart    62933 non-null  float64
 5   Week              67161 non-null  object
 6   Date              57451 non-null  object
 7   Genre             67161 non-null  object
 8   Writing.Credits   61436 non-null  object
 9   Lyrics            67161 non-null  object
 10  Features          10936 non-null  object
 11  Acousticness      67161 non-null  float64
 12  Album             67161 non-null  object
 13  Artist            67161 non-null  object
 14  Danceability      67161 non-null  float64
 15  Duration          67161 non-null  int64
 16  Energy            67161 non-null  float64
 17  Explicit          67161 non-null  bool
 18  Instrumentalness  67161 non-null  float64
 19  Liveness          67161 non-null  float64
 20  Loudness          67161 non-null  float64
 21  Mode              67161 non-null  int64
 22  Popularity        67161 non-null  int64
 23  Speechiness       67161 non-null  float64
 24  Tempo             67161 non-null  float64
 25  TimeSignature     67161 non-null  int64
 26  Valence           67161 non-null  float64
dtypes: bool(1), float64(11), int64(5), object(10)
memory usage: 13.9+ MB

In [12]:
new_df.drop(["Artist"], axis=1, inplace=True)

In [14]:
new_df.drop(["Date"], axis=1, inplace=True)

In [17]:
new_df.drop(["Writing.Credits"], axis=1, inplace=True)

In [18]:
new_df

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,Lyrics,Features,Acousticness,...,Explicit,Instrumentalness,Liveness,Loudness,Mode,Popularity,Speechiness,Tempo,TimeSignature,Valence
0,Jonas Brothers,Sucker,6,1.0,17.0,2019-07-06,"Alternative Pop,Boy Band,Teen Pop,Pop-Rock,Pop",Sucker \nWe go together\nBetter than birds of ...,NaN,0.042700,...,False,0.000000,0.1060,-5.065,0,81,0.0588,137.958,4,0.952
1,Jonas Brothers,Sucker,6,1.0,16.0,2019-06-29,"Alternative Pop,Boy Band,Teen Pop,Pop-Rock,Pop",Sucker \nWe go together\nBetter than birds of ...,NaN,0.042700,...,False,0.000000,0.1060,-5.065,0,81,0.0588,137.958,4,0.952
2,Jonas Brothers,Sucker,4,1.0,15.0,2019-06-22,"Alternative Pop,Boy Band,Teen Pop,Pop-Rock,Pop",Sucker \nWe go together\nBetter than birds of ...,NaN,0.042700,...,False,0.000000,0.1060,-5.065,0,81,0.0588,137.958,4,0.952
3,Jonas Brothers,Sucker,5,1.0,14.0,2019-06-15,"Alternative Pop,Boy Band,Teen Pop,Pop-Rock,Pop",Sucker \nWe go together\nBetter than birds of ...,NaN,0.042700,...,False,0.000000,0.1060,-5.065,0,81,0.0588,137.958,4,0.952
4,Jonas Brothers,Sucker,5,1.0,13.0,2019-06-08,"Alternative Pop,Boy Band,Teen Pop,Pop-Rock,Pop",Sucker \nWe go together\nBetter than birds of ...,NaN,0.042700,...,False,0.000000,0.1060,-5.065,0,81,0.0588,137.958,4,0.952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67156,Mark Wills,Wish You Were Here,81,34.0,20.0,1999-07-12,Country,Wish You Were Here \nThey kissed goodbye at th...,NaN,0.346000,...,False,0.000000,0.3910,-14.857,1,11,0.0310,136.094,4,0.272
67157,Mark Wills,Wish You Were Here,81,34.0,20.0,1999-07-12,Country,Wish You Were Here \nThey kissed goodbye at th...,NaN,0.190000,...,False,0.000000,0.1170,-10.234,1,41,0.0285,138.045,4,0.256
67158,Clay Walker,She's Always Right,85,74.0,6.0,1999-07-12,Pop,She's Always Right \nShe's Perfect for a cotto...,NaN,0.425000,...,False,0.000000,0.1430,-10.020,1,0,0.0315,142.685,4,0.480
67159,Collective Soul,Heavy,96,73.0,20.0,1999-07-12,"Hockey,Gaming,Soundtrack,Rock",Heavy \nComplicate this world you wrapped for ...,NaN,0.000877,...,False,0.000563,0.0839,-5.560,1,50,0.0371,106.923,4,0.548
67160,Collective Soul,Heavy,96,73.0,20.0,1999-07-12,"Hockey,Gaming,Soundtrack,Rock",Heavy \nComplicate this world you wrapped for ...,NaN,0.003480,...,False,0.573000,0.9770,-7.191,0,6,0.0495,108.080,4,0.361